DELIMITER //
CREATE PROCEDURE dbapi.sp_Payroll
(IN startdt DATE)
BEGIN


  select P.NAME,
    (SELECT SUM(HOURS) FROM dbo.WorkSchedule WS WHERE WS.PERSON = P.ID) AS HOURS,
    '2018-11-09' AS END_DATE,
    (SELECT WAGE FROM dbo.EmploymentHistory EH WHERE EH.PERSON = P.ID)*(SELECT SUM(HOURS) FROM dbo.WorkSchedule WS WHERE WS.PERSON = P.ID) AS AMOUNT
  from dbo.Person P;

END //
DELIMITER ;
